trigger:
- main  # ou seu branch principal

pool:
  vmImage: 'ubuntu-latest'  # ou outra imagem que você preferir

steps:
- task: Docker@2
  displayName: 'Executar a imagem Docker'
  inputs:
    command: 'run'
    containerRegistry: 'Docker Hub'  # sua conexão de serviço
    imageName: '2gsilva/my-movies-api:latest'
    options: '-d'

