version: '3'
services:
  api:
    image: "2gsilva/my-movies-api"
    ports:
      - "8080:80"
    networks:
      - webnet
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - webnet

networks:
  webnet: