name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build

    - name: Publish project
      run: dotnet publish -c Release -o dist
    
    - name: Set the Docker image tag
      run: echo "DOCKER_IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build --file "Dockerfile.dockerfile" --tag my-movies-api:$DOCKER_IMAGE_TAG "."

    - name: Login to Docker Hub
      run: docker login -u 2gsilva -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Publish Image to Docker Hub
      run: docker push 2gsilva/my-movies-api:$DOCKER_IMAGE_TAG
